name: Build Canary Release

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  action:
    uses: ./.github/workflows/build_action.yml
    secrets:
      CRX_PRIVATE_KEY: ${{ secrets.CRX_PRIVATE_KEY }}

  xpi:
    name: Build Xpi (Firefox)
    runs-on: ubuntu-latest
    needs: action
    outputs:
      exist_xpi_file: ${{ steps.addonsDeploy.outcome }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dev-build-${{ needs.action.outputs.version }}-zip

      - uses: cardinalby/webext-buildtools-firefox-sign-xpi-action@v1
        id: addonsDeploy
        if: ${{ env.FF_EXT_UUID != ''  }}
        env:
          FF_EXT_UUID: ${{ secrets.FF_EXT_UUID }}
        continue-on-error: true
        with:
          timeoutMs: 600000
          zipFilePath: extension.zip
          xpiFilePath: artifact/extension.signed.xpi
          extensionId: ${{ secrets.FF_EXT_UUID }}
          jwtIssuer: ${{ secrets.FF_JWT_ISSUER }}
          jwtSecret: ${{ secrets.FF_JWT_SECRET }}

      - name: Upload Built Xpi to action
        uses: actions/upload-artifact@v3
        if: ${{ steps.addonsDeploy.outcome == 'success' }}
        with:
          name: dev-build-${{ needs.zip.outputs.version }}-xpi
          path: artifact/*

  canary:
    runs-on: ubuntu-latest
    needs: [action, xpi]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Checkout gh-pages
        uses: actions/checkout@master
        with:
          ref: 'gh-pages'
          path: 'pages'

      - name: Prepare Release
        run: mkdir build

      - name: Get And rename Zip build
        uses: actions/download-artifact@v3
        with:
          name:
            dev-build-${{ needs.action.outputs.version }}-zip

      - run: mv extension.zip build/PT-Plugin-Plus-${{ needs.action.outputs.version }}.zip

      - name: Get And remove Crx Build
        uses: actions/download-artifact@v3
        with:
          name:
            dev-build-${{ needs.action.outputs.version }}-crx

      - run: |
          mv canary.xml pages/update/canary.xml -f
          mv extension.crx build/PT-Plugin-Plus-${{ needs.action.outputs.version }}.crx

      - name: Deploy update Xml
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pages
          commit_message: deploy ${{ github.ref }}
          force_orphan: true
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com

      - name: Get And move Xpi Build
        uses: actions/download-artifact@v3
        if: ${{ needs.xpi.outputs.exist_xpi_file == 'success' }}
        with:
          name:
            dev-build-${{ needs.action.outputs.version }}-xpi

      - if: ${{ needs.xpi.outputs.exist_xpi_file == 'success' }}
        run: mv extension.signed.xpi build/PT-Plugin-Plus-${{ needs.action.outputs.version }}.xpi

      - uses: ncipollo/release-action@v1
        with:
          name: v${{ needs.action.outputs.version }}
          tag: v${{ needs.action.outputs.version }}
          generateReleaseNotes: true
          prerelease: true
          artifacts: 'build/*'
